//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MvcApplication1.Models", "MerkArtikel", "Merk", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication1.Models.Merk), "Artikel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.Artikel))]
[assembly: EdmRelationshipAttribute("MvcApplication1.Models", "ShopModule", "Shop", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication1.Models.Shop), "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.Module))]
[assembly: EdmRelationshipAttribute("MvcApplication1.Models", "CategorieArtikel", "Categorie", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MvcApplication1.Models.Categorie), "Artikel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MvcApplication1.Models.Artikel))]

#endregion

namespace MvcApplication1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shop> Shops
        {
            get
            {
                if ((_Shops == null))
                {
                    _Shops = base.CreateObjectSet<Shop>("Shops");
                }
                return _Shops;
            }
        }
        private ObjectSet<Shop> _Shops;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Merk> Merks
        {
            get
            {
                if ((_Merks == null))
                {
                    _Merks = base.CreateObjectSet<Merk>("Merks");
                }
                return _Merks;
            }
        }
        private ObjectSet<Merk> _Merks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Artikel> Artikels
        {
            get
            {
                if ((_Artikels == null))
                {
                    _Artikels = base.CreateObjectSet<Artikel>("Artikels");
                }
                return _Artikels;
            }
        }
        private ObjectSet<Artikel> _Artikels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Categorie> Categories
        {
            get
            {
                if ((_Categories == null))
                {
                    _Categories = base.CreateObjectSet<Categorie>("Categories");
                }
                return _Categories;
            }
        }
        private ObjectSet<Categorie> _Categories;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shops EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShops(Shop shop)
        {
            base.AddObject("Shops", shop);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Merks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMerks(Merk merk)
        {
            base.AddObject("Merks", merk);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Artikels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToArtikels(Artikel artikel)
        {
            base.AddObject("Artikels", artikel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Categories EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCategories(Categorie categorie)
        {
            base.AddObject("Categories", categorie);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Artikel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Artikel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Artikel object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="isActief">Initial value of the IsActief property.</param>
        /// <param name="naamCommercieel">Initial value of the NaamCommercieel property.</param>
        /// <param name="isActiefInModule">Initial value of the IsActiefInModule property.</param>
        /// <param name="isActiefInLosseGsm">Initial value of the IsActiefInLosseGsm property.</param>
        /// <param name="isActiefInGsmAbo">Initial value of the IsActiefInGsmAbo property.</param>
        public static Artikel CreateArtikel(global::System.Int32 id, global::System.Boolean isActief, global::System.String naamCommercieel, global::System.Int16 isActiefInModule, global::System.Boolean isActiefInLosseGsm, global::System.Boolean isActiefInGsmAbo)
        {
            Artikel artikel = new Artikel();
            artikel.Id = id;
            artikel.IsActief = isActief;
            artikel.NaamCommercieel = naamCommercieel;
            artikel.IsActiefInModule = isActiefInModule;
            artikel.IsActiefInLosseGsm = isActiefInLosseGsm;
            artikel.IsActiefInGsmAbo = isActiefInGsmAbo;
            return artikel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActief
        {
            get
            {
                return _IsActief;
            }
            set
            {
                OnIsActiefChanging(value);
                ReportPropertyChanging("IsActief");
                _IsActief = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActief");
                OnIsActiefChanged();
            }
        }
        private global::System.Boolean _IsActief;
        partial void OnIsActiefChanging(global::System.Boolean value);
        partial void OnIsActiefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NaamCommercieel
        {
            get
            {
                return _NaamCommercieel;
            }
            set
            {
                OnNaamCommercieelChanging(value);
                ReportPropertyChanging("NaamCommercieel");
                _NaamCommercieel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NaamCommercieel");
                OnNaamCommercieelChanged();
            }
        }
        private global::System.String _NaamCommercieel;
        partial void OnNaamCommercieelChanging(global::System.String value);
        partial void OnNaamCommercieelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 IsActiefInModule
        {
            get
            {
                return _IsActiefInModule;
            }
            set
            {
                OnIsActiefInModuleChanging(value);
                ReportPropertyChanging("IsActiefInModule");
                _IsActiefInModule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActiefInModule");
                OnIsActiefInModuleChanged();
            }
        }
        private global::System.Int16 _IsActiefInModule;
        partial void OnIsActiefInModuleChanging(global::System.Int16 value);
        partial void OnIsActiefInModuleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActiefInLosseGsm
        {
            get
            {
                return _IsActiefInLosseGsm;
            }
            set
            {
                OnIsActiefInLosseGsmChanging(value);
                ReportPropertyChanging("IsActiefInLosseGsm");
                _IsActiefInLosseGsm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActiefInLosseGsm");
                OnIsActiefInLosseGsmChanged();
            }
        }
        private global::System.Boolean _IsActiefInLosseGsm;
        partial void OnIsActiefInLosseGsmChanging(global::System.Boolean value);
        partial void OnIsActiefInLosseGsmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActiefInGsmAbo
        {
            get
            {
                return _IsActiefInGsmAbo;
            }
            set
            {
                OnIsActiefInGsmAboChanging(value);
                ReportPropertyChanging("IsActiefInGsmAbo");
                _IsActiefInGsmAbo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActiefInGsmAbo");
                OnIsActiefInGsmAboChanged();
            }
        }
        private global::System.Boolean _IsActiefInGsmAbo;
        partial void OnIsActiefInGsmAboChanging(global::System.Boolean value);
        partial void OnIsActiefInGsmAboChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "MerkArtikel", "Merk")]
        public Merk Merk
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merk>("MvcApplication1.Models.MerkArtikel", "Merk").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merk>("MvcApplication1.Models.MerkArtikel", "Merk").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Merk> MerkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Merk>("MvcApplication1.Models.MerkArtikel", "Merk");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Merk>("MvcApplication1.Models.MerkArtikel", "Merk", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "CategorieArtikel", "Categorie")]
        public Categorie Categorie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorie>("MvcApplication1.Models.CategorieArtikel", "Categorie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorie>("MvcApplication1.Models.CategorieArtikel", "Categorie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Categorie> CategorieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Categorie>("MvcApplication1.Models.CategorieArtikel", "Categorie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Categorie>("MvcApplication1.Models.CategorieArtikel", "Categorie", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Categorie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Categorie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Categorie object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        public static Categorie CreateCategorie(global::System.Int32 id, global::System.String naam)
        {
            Categorie categorie = new Categorie();
            categorie.Id = id;
            categorie.Naam = naam;
            return categorie;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "CategorieArtikel", "Artikel")]
        public EntityCollection<Artikel> Artikels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Artikel>("MvcApplication1.Models.CategorieArtikel", "Artikel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Artikel>("MvcApplication1.Models.CategorieArtikel", "Artikel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Merk")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Merk : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Merk object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        /// <param name="naamCommercieel">Initial value of the NaamCommercieel property.</param>
        /// <param name="afbeeldingKlein">Initial value of the AfbeeldingKlein property.</param>
        /// <param name="naamInUrl">Initial value of the NaamInUrl property.</param>
        /// <param name="volgNummer">Initial value of the VolgNummer property.</param>
        /// <param name="isActief">Initial value of the IsActief property.</param>
        /// <param name="isActiefInModule">Initial value of the IsActiefInModule property.</param>
        public static Merk CreateMerk(global::System.Int32 id, global::System.String naam, global::System.String naamCommercieel, global::System.String afbeeldingKlein, global::System.String naamInUrl, global::System.Int32 volgNummer, global::System.Boolean isActief, global::System.Int32 isActiefInModule)
        {
            Merk merk = new Merk();
            merk.Id = id;
            merk.Naam = naam;
            merk.NaamCommercieel = naamCommercieel;
            merk.AfbeeldingKlein = afbeeldingKlein;
            merk.NaamInUrl = naamInUrl;
            merk.VolgNummer = volgNummer;
            merk.IsActief = isActief;
            merk.IsActiefInModule = isActiefInModule;
            return merk;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NaamCommercieel
        {
            get
            {
                return _NaamCommercieel;
            }
            set
            {
                OnNaamCommercieelChanging(value);
                ReportPropertyChanging("NaamCommercieel");
                _NaamCommercieel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NaamCommercieel");
                OnNaamCommercieelChanged();
            }
        }
        private global::System.String _NaamCommercieel;
        partial void OnNaamCommercieelChanging(global::System.String value);
        partial void OnNaamCommercieelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AfbeeldingKlein
        {
            get
            {
                return _AfbeeldingKlein;
            }
            set
            {
                OnAfbeeldingKleinChanging(value);
                ReportPropertyChanging("AfbeeldingKlein");
                _AfbeeldingKlein = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AfbeeldingKlein");
                OnAfbeeldingKleinChanged();
            }
        }
        private global::System.String _AfbeeldingKlein;
        partial void OnAfbeeldingKleinChanging(global::System.String value);
        partial void OnAfbeeldingKleinChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NaamInUrl
        {
            get
            {
                return _NaamInUrl;
            }
            set
            {
                OnNaamInUrlChanging(value);
                ReportPropertyChanging("NaamInUrl");
                _NaamInUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NaamInUrl");
                OnNaamInUrlChanged();
            }
        }
        private global::System.String _NaamInUrl;
        partial void OnNaamInUrlChanging(global::System.String value);
        partial void OnNaamInUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VolgNummer
        {
            get
            {
                return _VolgNummer;
            }
            set
            {
                OnVolgNummerChanging(value);
                ReportPropertyChanging("VolgNummer");
                _VolgNummer = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VolgNummer");
                OnVolgNummerChanged();
            }
        }
        private global::System.Int32 _VolgNummer;
        partial void OnVolgNummerChanging(global::System.Int32 value);
        partial void OnVolgNummerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActief
        {
            get
            {
                return _IsActief;
            }
            set
            {
                OnIsActiefChanging(value);
                ReportPropertyChanging("IsActief");
                _IsActief = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActief");
                OnIsActiefChanged();
            }
        }
        private global::System.Boolean _IsActief;
        partial void OnIsActiefChanging(global::System.Boolean value);
        partial void OnIsActiefChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IsActiefInModule
        {
            get
            {
                return _IsActiefInModule;
            }
            set
            {
                OnIsActiefInModuleChanging(value);
                ReportPropertyChanging("IsActiefInModule");
                _IsActiefInModule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActiefInModule");
                OnIsActiefInModuleChanged();
            }
        }
        private global::System.Int32 _IsActiefInModule;
        partial void OnIsActiefInModuleChanging(global::System.Int32 value);
        partial void OnIsActiefInModuleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "MerkArtikel", "Artikel")]
        public EntityCollection<Artikel> Artikels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Artikel>("MvcApplication1.Models.MerkArtikel", "Artikel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Artikel>("MvcApplication1.Models.MerkArtikel", "Artikel", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Module object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="naam">Initial value of the Naam property.</param>
        /// <param name="moduleByteValue">Initial value of the ModuleByteValue property.</param>
        public static Module CreateModule(global::System.Int32 id, global::System.String naam, global::System.Int32 moduleByteValue)
        {
            Module module = new Module();
            module.Id = id;
            module.Naam = naam;
            module.ModuleByteValue = moduleByteValue;
            return module;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Naam
        {
            get
            {
                return _Naam;
            }
            set
            {
                OnNaamChanging(value);
                ReportPropertyChanging("Naam");
                _Naam = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Naam");
                OnNaamChanged();
            }
        }
        private global::System.String _Naam;
        partial void OnNaamChanging(global::System.String value);
        partial void OnNaamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleByteValue
        {
            get
            {
                return _ModuleByteValue;
            }
            set
            {
                OnModuleByteValueChanging(value);
                ReportPropertyChanging("ModuleByteValue");
                _ModuleByteValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleByteValue");
                OnModuleByteValueChanged();
            }
        }
        private global::System.Int32 _ModuleByteValue;
        partial void OnModuleByteValueChanging(global::System.Int32 value);
        partial void OnModuleByteValueChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "ShopModule", "Shop")]
        public Shop Shop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("MvcApplication1.Models.ShopModule", "Shop").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("MvcApplication1.Models.ShopModule", "Shop").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Shop> ShopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Shop>("MvcApplication1.Models.ShopModule", "Shop");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Shop>("MvcApplication1.Models.ShopModule", "Shop", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MvcApplication1.Models", Name="Shop")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shop : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shop object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Shop CreateShop(global::System.Int32 id)
        {
            Shop shop = new Shop();
            shop.Id = id;
            return shop;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MvcApplication1.Models", "ShopModule", "Module")]
        public EntityCollection<Module> Modules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Module>("MvcApplication1.Models.ShopModule", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Module>("MvcApplication1.Models.ShopModule", "Module", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
